export const animalData = [
  {
    name: "Lion",
    habitat: "Savannah",
    diet: "Carnivore",
    size: "Large",
    movement: "Walks",
    emoji: "🦁",
  },
  {
    name: "Eagle",
    habitat: "Forest",
    diet: "Carnivore",
    size: "Medium",
    movement: "Flies",
    emoji: "🦅",
  },
  {
    name: "Elephant",
    habitat: "Grassland",
    diet: "Herbivore",
    size: "Gigantic",
    movement: "Walks",
    emoji: "🐘",
  },
  {
    name: "Shark",
    habitat: "Ocean",
    diet: "Carnivore",
    size: "Large",
    movement: "Swims",
    emoji: "🦈",
  },
  {
    name: "Turtle",
    habitat: "Freshwater",
    diet: "Herbivore",
    size: "Small",
    movement: "Crawls",
    emoji: "🐢",
  },
  {
    name: "Wolf",
    habitat: "Forest",
    diet: "Carnivore",
    size: "Medium",
    movement: "Walks",
    emoji: "🐺",
  },
  {
    name: "Penguin",
    habitat: "Arctic",
    diet: "Carnivore",
    size: "Medium",
    movement: "Walks & Swims",
    emoji: "🐧",
  },
  {
    name: "Dolphin",
    habitat: "Ocean",
    diet: "Carnivore",
    size: "Large",
    movement: "Swims",
    emoji: "🐬",
  },
  {
    name: "Kangaroo",
    habitat: "Grassland",
    diet: "Herbivore",
    size: "Medium",
    movement: "Hops",
    emoji: "🦘",
  },
  {
    name: "Panda",
    habitat: "Forest",
    diet: "Herbivore",
    size: "Large",
    movement: "Walks",
    emoji: "🐼",
  },
  {
    name: "Crocodile",
    habitat: "Freshwater",
    diet: "Carnivore",
    size: "Large",
    movement: "Crawls & Swims",
    emoji: "🐊",
  },
  {
    name: "Giraffe",
    habitat: "Savannah",
    diet: "Herbivore",
    size: "Gigantic",
    movement: "Walks",
    emoji: "🦒",
  },
  {
    name: "Octopus",
    habitat: "Ocean",
    diet: "Carnivore",
    size: "Medium",
    movement: "Swims",
    emoji: "🐙",
  },
  {
    name: "Rabbit",
    habitat: "Forest",
    diet: "Herbivore",
    size: "Small",
    movement: "Hops",
    emoji: "🐰",
  },
  {
    name: "Bear",
    habitat: "Forest",
    diet: "Omnivore",
    size: "Large",
    movement: "Walks",
    emoji: "🐻",
  },
  {
    name: "Snake",
    habitat: "Desert",
    diet: "Carnivore",
    size: "Medium",
    movement: "Crawls",
    emoji: "🐍",
  },
  {
    name: "Horse",
    habitat: "Grassland",
    diet: "Herbivore",
    size: "Large",
    movement: "Walks & Runs",
    emoji: "🐴",
  },
  {
    name: "Chimpanzee",
    habitat: "Forest",
    diet: "Omnivore",
    size: "Medium",
    movement: "Walks & Climbs",
    emoji: "🐵",
  },
  {
    name: "Whale",
    habitat: "Ocean",
    diet: "Carnivore",
    size: "Gigantic",
    movement: "Swims",
    emoji: "🐋",
  },
];
