export const bollywoodData = [
  {
    name: "Lagaan",
    genre: "Sports",
    release_year: "2001",
    director: "Ashutosh Gowariker",
    lead_actor: "Aamir Khan",
    lead_actress: "Gracy Singh",
    emoji: "🏏",
  },
  {
    name: "Kabhi Khushi Kabhie Gham",
    genre: "Family Drama",
    release_year: "2001",
    director: "Karan Johar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Kajol",
    emoji: "👨‍👩‍👧‍👦",
  },
  {
    name: "Devdas",
    genre: "Romance",
    release_year: "2002",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Aishwarya Rai",
    emoji: "🥃",
  },
  {
    name: "Kal Ho Naa Ho",
    genre: "Romance",
    release_year: "2003",
    director: "Nikkhil Advani",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Preity Zinta",
    emoji: "💔",
  },
  {
    name: "Dhoom",
    genre: "Action",
    release_year: "2004",
    director: "Sanjay Gadhvi",
    lead_actor: "Abhishek Bachchan",
    lead_actress: "Esha Deol",
    emoji: "🏍️",
  },
  {
    name: "Black",
    genre: "Drama",
    release_year: "2005",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Amitabh Bachchan",
    lead_actress: "Rani Mukerji",
    emoji: "🖤",
  },
  {
    name: "Rang De Basanti",
    genre: "Drama",
    release_year: "2006",
    director: "Rakeysh Omprakash Mehra",
    lead_actor: "Aamir Khan",
    lead_actress: "Soha Ali Khan",
    emoji: "🇮🇳",
  },
  {
    name: "Chak De India",
    genre: "Sports",
    release_year: "2007",
    director: "Shimit Amin",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Vidya Malvade",
    emoji: "🏑",
  },
  {
    name: "Jab We Met",
    genre: "Romance",
    release_year: "2007",
    director: "Imtiaz Ali",
    lead_actor: "Shahid Kapoor",
    lead_actress: "Kareena Kapoor",
    emoji: "🚂",
  },
  {
    name: "Taare Zameen Par",
    genre: "Drama",
    release_year: "2007",
    director: "Aamir Khan",
    lead_actor: "Aamir Khan",
    lead_actress: "Tisca Chopra",
    emoji: "🎨",
  },
  {
    name: "3 Idiots",
    genre: "Comedy",
    release_year: "2009",
    director: "Rajkumar Hirani",
    lead_actor: "Aamir Khan",
    lead_actress: "Kareena Kapoor",
    emoji: "🎓",
  },
  {
    name: "My Name Is Khan",
    genre: "Drama",
    release_year: "2010",
    director: "Karan Johar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Kajol",
    emoji: "✈️",
  },
  {
    name: "Zindagi Na Milegi Dobara",
    genre: "Drama",
    release_year: "2011",
    director: "Zoya Akhtar",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Katrina Kaif",
    emoji: "🏄‍♂️",
  },
  {
    name: "Barfi",
    genre: "Drama",
    release_year: "2012",
    director: "Anurag Basu",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Priyanka Chopra",
    emoji: "🍬",
  },
  {
    name: "Queen",
    genre: "Drama",
    release_year: "2014",
    director: "Vikas Bahl",
    lead_actor: "Rajkummar Rao",
    lead_actress: "Kangana Ranaut",
    emoji: "👑",
  },
  {
    name: "PK",
    genre: "Comedy",
    release_year: "2014",
    director: "Rajkumar Hirani",
    lead_actor: "Aamir Khan",
    lead_actress: "Anushka Sharma",
    emoji: "👽",
  },
  {
    name: "Bajrangi Bhaijaan",
    genre: "Drama",
    release_year: "2015",
    director: "Kabir Khan",
    lead_actor: "Salman Khan",
    lead_actress: "Kareena Kapoor",
    emoji: "🙏",
  },
  {
    name: "Dangal",
    genre: "Sports",
    release_year: "2016",
    director: "Nitesh Tiwari",
    lead_actor: "Aamir Khan",
    lead_actress: "Fatima Sana Shaikh, Sanya Malhotra",
    emoji: "🤼‍♀️",
  },
  {
    name: "Raees",
    genre: "Action",
    release_year: "2017",
    director: "Rahul Dholakia",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Mahira Khan",
    emoji: "🤑",
  },
  {
    name: "Padmaavat",
    genre: "Drama",
    release_year: "2018",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Ranveer Singh",
    lead_actress: "Deepika Padukone",
    emoji: "👸",
  },
  {
    name: "Gully Boy",
    genre: "Biopic",
    release_year: "2019",
    director: "Zoya Akhtar",
    lead_actor: "Ranveer Singh",
    lead_actress: "Alia Bhatt",
    emoji: "🎤",
  },
  {
    name: "Uri",
    genre: "Action",
    release_year: "2019",
    director: "Aditya Dhar",
    lead_actor: "Vicky Kaushal",
    lead_actress: "Yami Gautam",
    emoji: "🪖",
  },
  {
    name: "Tanhaji",
    genre: "Biopic",
    release_year: "2020",
    director: "Om Raut",
    lead_actor: "Ajay Devgn",
    lead_actress: "Kajol",
    emoji: "⚔️",
  },
  {
    name: "Ludo",
    genre: "Drama",
    release_year: "2020",
    director: "Anurag Basu",
    lead_actor: "Abhishek Bachchan, Rajkummar Rao",
    lead_actress: "Fatima Sana Shaikh, Sanya Malhotra",
    emoji: "🎲",
  },
  // 2021
  {
    name: "Shershaah",
    genre: "Biopic",
    release_year: "2021",
    director: "Vishnuvardhan",
    lead_actor: "Sidharth Malhotra",
    lead_actress: "Kiara Advani",
    emoji: "🪖",
  },
  {
    name: "83",
    genre: "Biopic",
    release_year: "2021",
    director: "Kabir Khan",
    lead_actor: "Ranveer Singh",
    lead_actress: "Deepika Padukone",
    emoji: "🏏",
  },
  // 2022
  {
    name: "Gangubai Kathiawadi",
    genre: "Biopic",
    release_year: "2022",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Ajay Devgn",
    lead_actress: "Alia Bhatt",
    emoji: "👑",
  },
  {
    name: "Vikram Vedha",
    genre: "Action",
    release_year: "2022",
    director: "Pushkar, Gayatri",
    lead_actor: "Hrithik Roshan, Saif Ali Khan",
    lead_actress: "Radhika Apte",
    emoji: "🔫",
  },
  // 2023
  {
    name: "Animal",
    genre: "Action",
    release_year: "2023",
    director: "Sandeep Reddy Vanga",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Rashmika Mandanna",
    emoji: "🦁",
  },
  {
    name: "12th Fail",
    genre: "Biopic",
    release_year: "2023",
    director: "Vidhu Vinod Chopra",
    lead_actor: "Vikrant Massey",
    lead_actress: "Medha Shankar",
    emoji: "📖",
  },
  {
    name: "Jawan",
    genre: "Action",
    release_year: "2023",
    director: "Atlee",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Nayanthara",
    emoji: "💣",
  },
  {
    name: "Dunki",
    genre: "Drama",
    release_year: "2023",
    director: "Rajkumar Hirani",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Taapsee Pannu",
    emoji: "🌍",
  },
  {
    name: "Rocky Aur Rani Ki Prem Kahani",
    genre: "Romance",
    release_year: "2023",
    director: "Karan Johar",
    lead_actor: "Ranveer Singh",
    lead_actress: "Alia Bhatt",
    emoji: "💖",
  },
  //more movies
  {
    name: "Swades",
    genre: "Drama",
    release_year: "2004",
    director: "Ashutosh Gowariker",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Gayatri Joshi",
    emoji: "🌍",
  },
  {
    name: "Don",
    genre: "Action",
    release_year: "2006",
    director: "Farhan Akhtar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Priyanka Chopra",
    emoji: "🕶️",
  },
  {
    name: "Wake Up Sid",
    genre: "Coming of Age",
    release_year: "2009",
    director: "Ayan Mukerji",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Konkona Sen Sharma",
    emoji: "🌅",
  },
  {
    name: "Band Baaja Baaraat",
    genre: "Romance",
    release_year: "2010",
    director: "Maneesh Sharma",
    lead_actor: "Ranveer Singh",
    lead_actress: "Anushka Sharma",
    emoji: "💒",
  },
  {
    name: "Highway",
    genre: "Drama",
    release_year: "2014",
    director: "Imtiaz Ali",
    lead_actor: "Randeep Hooda",
    lead_actress: "Alia Bhatt",
    emoji: "🚗",
  },
  {
    name: "Andhadhun",
    genre: "Thriller",
    release_year: "2018",
    director: "Sriram Raghavan",
    lead_actor: "Ayushmann Khurrana",
    lead_actress: "Tabu",
    emoji: "🎹",
  },
  {
    name: "Thappad",
    genre: "Social Drama",
    release_year: "2020",
    director: "Anubhav Sinha",
    lead_actor: "Pavail Gulati",
    lead_actress: "Taapsee Pannu",
    emoji: "👋",
  },
  {
    name: "Dil Bechara",
    genre: "Romance",
    release_year: "2020",
    director: "Mukesh Chhabra",
    lead_actor: "Sushant Singh Rajput",
    lead_actress: "Sanjana Sanghi",
    emoji: "💖",
  },
  {
    name: "Gehraiyaan",
    genre: "Relationship Drama",
    release_year: "2022",
    director: "Shakun Batra",
    lead_actor: "Siddhant Chaturvedi",
    lead_actress: "Deepika Padukone",
    emoji: "🌊",
  },
  {
    name: "Mimi",
    genre: "Comedy Drama",
    release_year: "2021",
    director: "Laxman Utekar",
    lead_actor: "Pankaj Tripathi",
    lead_actress: "Kriti Sanon",
    emoji: "👶",
  },
  {
    name: "Bell Bottom",
    genre: "Spy Thriller",
    release_year: "2021",
    director: "Ranjit M Tewari",
    lead_actor: "Akshay Kumar",
    lead_actress: "Vaani Kapoor",
    emoji: "🕵️",
  }
]

