export const bollywoodData = [
  {
    name: "Lagaan",
    genre: "Sports",
    release_year: "2001",
    director: "Ashutosh Gowariker",
    lead_actor: "Aamir Khan",
    lead_actress: "Gracy Singh",
    emoji: "🏏",
    fact: "Lagaan was only the third Indian film to be nominated for an Academy Award for Best Foreign Language Film.",
  },
  {
    name: "Kabhi Khushi Kabhie Gham",
    genre: "Family Drama",
    release_year: "2001",
    director: "Karan Johar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Kajol",
    emoji: "👨‍👩‍👧‍👦",
    fact: "K3G, as it's popularly known, was the highest-grossing Indian film internationally at the time of its release.",
  },
  {
    name: "Devdas",
    genre: "Romance",
    release_year: "2002",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Aishwarya Rai",
    emoji: "🥃",
    fact: "Devdas was the most expensive Bollywood film ever made at the time, with a budget of over 50 crore rupees.",
  },
  {
    name: "Kal Ho Naa Ho",
    genre: "Romance",
    release_year: "2003",
    director: "Nikkhil Advani",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Preity Zinta",
    emoji: "💔",
    fact: "The film was shot primarily in New York City and was one of the first major Bollywood productions to be set entirely overseas.",
  },
  {
    name: "Dhoom",
    genre: "Action",
    release_year: "2004",
    director: "Sanjay Gadhvi",
    lead_actor: "Abhishek Bachchan",
    lead_actress: "Esha Deol",
    emoji: "🏍️",
    fact: "Dhoom spawned one of Bollywood's most successful franchises, with each sequel breaking box office records.",
  },
  {
    name: "Black",
    genre: "Drama",
    release_year: "2005",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Amitabh Bachchan",
    lead_actress: "Rani Mukerji",
    emoji: "🖤",
    fact: "Black was inspired by the life of Helen Keller and was shot in a record 60 days.",
  },
  {
    name: "Rang De Basanti",
    genre: "Drama",
    release_year: "2006",
    director: "Rakeysh Omprakash Mehra",
    lead_actor: "Aamir Khan",
    lead_actress: "Soha Ali Khan",
    emoji: "🇮🇳",
    fact: "The film inspired real-life protests and political movements in India, including candle-light vigils.",
  },
  {
    name: "Chak De India",
    genre: "Sports",
    release_year: "2007",
    director: "Shimit Amin",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Vidya Malvade",
    emoji: "🏑",
    fact: "Many of the actresses in the film underwent intensive hockey training for 3-4 months to make the sports scenes authentic.",
  },
  {
    name: "Jab We Met",
    genre: "Romance",
    release_year: "2007",
    director: "Imtiaz Ali",
    lead_actor: "Shahid Kapoor",
    lead_actress: "Kareena Kapoor",
    emoji: "🚂",
    fact: "The film was shot in over 35 different locations across India, capturing the essence of a cross-country journey.",
  },
  {
    name: "Taare Zameen Par",
    genre: "Drama",
    release_year: "2007",
    director: "Aamir Khan",
    lead_actor: "Aamir Khan",
    lead_actress: "Tisca Chopra",
    emoji: "🎨",
    fact: "This was Aamir Khan's directorial debut, and the film raised awareness about dyslexia across India.",
  },
  {
    name: "3 Idiots",
    genre: "Comedy",
    release_year: "2009",
    director: "Rajkumar Hirani",
    lead_actor: "Aamir Khan",
    lead_actress: "Kareena Kapoor",
    emoji: "🎓",
    fact: "3 Idiots was the first Bollywood film to earn over 400 crore rupees worldwide and sparked educational reforms in India.",
  },
  {
    name: "My Name Is Khan",
    genre: "Drama",
    release_year: "2010",
    director: "Karan Johar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Kajol",
    emoji: "✈️",
    fact: "The film premiered at the 60th Berlin International Film Festival, the first Bollywood film to open at this prestigious event.",
  },
  {
    name: "Zindagi Na Milegi Dobara",
    genre: "Drama",
    release_year: "2011",
    director: "Zoya Akhtar",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Katrina Kaif",
    emoji: "🏄‍♂️",
    fact: "The film boosted tourism to Spain by 65% among Indian travelers after its release.",
  },
  {
    name: "Barfi",
    genre: "Drama",
    release_year: "2012",
    director: "Anurag Basu",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Priyanka Chopra",
    emoji: "🍬",
    fact: "Ranbir Kapoor's character doesn't speak a single word throughout the film, yet delivers one of his most acclaimed performances.",
  },
  {
    name: "Queen",
    genre: "Drama",
    release_year: "2014",
    director: "Vikas Bahl",
    lead_actor: "Rajkummar Rao",
    lead_actress: "Kangana Ranaut",
    emoji: "👑",
    fact: "The film was shot guerrilla-style in Paris and Amsterdam with a small crew to maintain authenticity.",
  },
  {
    name: "PK",
    genre: "Comedy",
    release_year: "2014",
    director: "Rajkumar Hirani",
    lead_actor: "Aamir Khan",
    lead_actress: "Anushka Sharma",
    emoji: "👽",
    fact: "PK became the first Indian film to gross over 700 crore rupees worldwide and sparked nationwide debates on religion.",
  },
  {
    name: "Bajrangi Bhaijaan",
    genre: "Drama",
    release_year: "2015",
    director: "Kabir Khan",
    lead_actor: "Salman Khan",
    lead_actress: "Kareena Kapoor",
    emoji: "🙏",
    fact: "The child actress Harshaali Malhotra was selected from over 5,000 girls who auditioned for the role of Munni.",
  },
  {
    name: "Dangal",
    genre: "Sports",
    release_year: "2016",
    director: "Nitesh Tiwari",
    lead_actor: "Aamir Khan",
    lead_actress: "Fatima Sana Shaikh, Sanya Malhotra",
    emoji: "🤼‍♀️",
    fact: "Aamir Khan gained 30kg for his role and then lost it all in just 5 months for different portions of the film.",
  },
  {
    name: "Raees",
    genre: "Action",
    release_year: "2017",
    director: "Rahul Dholakia",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Mahira Khan",
    emoji: "🤑",
    fact: "Shah Rukh Khan performed many of his own stunts in the film despite suffering a knee injury during production.",
  },
  {
    name: "Padmaavat",
    genre: "Drama",
    release_year: "2018",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Ranveer Singh",
    lead_actress: "Deepika Padukone",
    emoji: "👸",
    fact: "The film faced massive protests and was banned in several states before its release due to historical controversies.",
  },
  {
    name: "Gully Boy",
    genre: "Biopic",
    release_year: "2019",
    director: "Zoya Akhtar",
    lead_actor: "Ranveer Singh",
    lead_actress: "Alia Bhatt",
    emoji: "🎤",
    fact: "Ranveer Singh recorded all his rap songs for the film himself after undergoing extensive training with real street rappers.",
  },
  {
    name: "Ludo",
    genre: "Drama",
    release_year: "2020",
    director: "Anurag Basu",
    lead_actor: "Abhishek Bachchan, Rajkummar Rao",
    lead_actress: "Fatima Sana Shaikh, Sanya Malhotra",
    emoji: "🎲",
    fact: "The film interweaves four different stories, with each story represented by a different color from the Ludo board game.",
  },
  {
    name: "Shershaah",
    genre: "Biopic",
    release_year: "2021",
    director: "Vishnuvardhan",
    lead_actor: "Sidharth Malhotra",
    lead_actress: "Kiara Advani",
    emoji: "🪖",
    fact: "The film is based on the life of Vikram Batra, who was posthumously awarded the Param Vir Chakra for his actions during the 1999 Kargil War.",
  },
  {
    name: "Gangubai Kathiawadi",
    genre: "Biopic",
    release_year: "2022",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Ajay Devgn",
    lead_actress: "Alia Bhatt",
    emoji: "👑",
    fact: "Alia Bhatt prepared for her role by studying vintage photographs and meeting sex workers to understand their lives and mannerisms.",
  },
  {
    name: "Animal",
    genre: "Action",
    release_year: "2023",
    director: "Sandeep Reddy Vanga",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Rashmika Mandanna",
    emoji: "🦁",
    fact: "Ranbir Kapoor underwent a dramatic physical transformation for this role, gaining substantial muscle mass over several months of training.",
  },
  {
    name: "Jawan",
    genre: "Action",
    release_year: "2023",
    director: "Atlee",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Nayanthara",
    emoji: "💣",
    fact: "Shah Rukh Khan played a dual role in the film and spent over 7 hours in makeup daily for one of his characters.",
  },
  {
    name: "Dunki",
    genre: "Drama",
    release_year: "2023",
    director: "Rajkumar Hirani",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Taapsee Pannu",
    emoji: "🌍",
    fact: "This film marked the first collaboration between Shah Rukh Khan and director Rajkumar Hirani after decades in the industry.",
  },
  {
    name: "Rocky Aur Rani Ki Prem Kahani",
    genre: "Romance",
    release_year: "2023",
    director: "Karan Johar",
    lead_actor: "Ranveer Singh",
    lead_actress: "Alia Bhatt",
    emoji: "💖",
    fact: "This film marked Karan Johar's return to directing after a seven-year break since his last feature film.",
  },
  {
    name: "Swades",
    genre: "Drama",
    release_year: "2004",
    director: "Ashutosh Gowariker",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Gayatri Joshi",
    emoji: "🌍",
    fact: "Despite underperforming at the box office initially, Swades is now considered one of Shah Rukh Khan's finest performances and a cult classic.",
  },
  {
    name: "Don",
    genre: "Action",
    release_year: "2006",
    director: "Farhan Akhtar",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Priyanka Chopra",
    emoji: "🕶️",
    fact: "The film was a remake of the 1978 classic of the same name starring Amitabh Bachchan, but with a completely different ending that surprised audiences.",
  },
  {
    name: "Wake Up Sid",
    genre: "Coming of Age",
    release_year: "2009",
    director: "Ayan Mukerji",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Konkona Sen Sharma",
    emoji: "🌅",
    fact: "The film was shot in over 50 real locations across Mumbai, giving it an authentic feel rather than using studio sets.",
  },
  {
    name: "Band Baaja Baaraat",
    genre: "Romance",
    release_year: "2010",
    director: "Maneesh Sharma",
    lead_actor: "Ranveer Singh",
    lead_actress: "Anushka Sharma",
    emoji: "💒",
    fact: "This was Ranveer Singh's debut film, and he actually worked as a wedding planner's assistant to prepare for his role.",
  },
  {
    name: "Highway",
    genre: "Drama",
    release_year: "2014",
    director: "Imtiaz Ali",
    lead_actor: "Randeep Hooda",
    lead_actress: "Alia Bhatt",
    emoji: "🚗",
    fact: "The film was shot in sequence, with the team traveling over 15,000 kilometers across six different Indian states.",
  },
  {
    name: "Andhadhun",
    genre: "Thriller",
    release_year: "2018",
    director: "Sriram Raghavan",
    lead_actor: "Ayushmann Khurrana",
    lead_actress: "Tabu",
    emoji: "🎹",
    fact: "Ayushmann Khurrana learned to play the piano for three months to authentically portray a blind pianist in the film.",
  },
  {
    name: "Gehraiyaan",
    genre: "Relationship Drama",
    release_year: "2022",
    director: "Shakun Batra",
    lead_actor: "Siddhant Chaturvedi",
    lead_actress: "Deepika Padukone",
    emoji: "🌊",
    fact: "The film employed an intimacy coordinator for the first time in Indian cinema to ensure the actors' comfort during intimate scenes.",
  },
  {
    name: "Brahmastra",
    genre: "Fantasy Adventure",
    release_year: "2022",
    director: "Ayan Mukerji",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Alia Bhatt",
    emoji: "🔥",
    fact: "The film took over 5 years to make and is part of a planned trilogy that combines Indian mythology with modern fantasy elements.",
  },
  {
    name: "Pathaan",
    genre: "Action Thriller",
    release_year: "2023",
    director: "Siddharth Anand",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Deepika Padukone",
    emoji: "🔫",
    fact: "Pathaan marked Shah Rukh Khan's return to the big screen after a four-year hiatus and became one of the highest-grossing Hindi films of all time.",
  },
  {
    name: "Koi Mil Gaya",
    genre: "Sci-Fi",
    release_year: "2003",
    director: "Rakesh Roshan",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Preity Zinta",
    emoji: "👽",
    fact: "The film's alien character Jadoo took over six months to design and required multiple puppeteers to operate during filming.",
  },
  {
    name: "Om Shanti Om",
    genre: "Drama",
    release_year: "2007",
    director: "Farah Khan",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Deepika Padukone",
    emoji: "🔥",
    fact: "The film featured cameos from over 30 Bollywood celebrities in a single song sequence, making it one of the largest star gatherings ever filmed.",
  },
  {
    name: "Ghajini",
    genre: "Action",
    release_year: "2008",
    director: "A.R. Murugadoss",
    lead_actor: "Aamir Khan",
    lead_actress: "Asin",
    emoji: "🧠",
    fact: "Aamir Khan built an incredible physique for the film, working out for over a year to achieve the muscular look required for his character.",
  },
  {
    name: "Yeh Jawaani Hai Deewani",
    genre: "Romance",
    release_year: "2013",
    director: "Ayan Mukerji",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Deepika Padukone",
    emoji: "🎉",
    fact: "The breathtaking trekking scenes were shot in the challenging conditions of Manali during winter, with temperatures often dropping below freezing.",
  },
  {
    name: "Bajirao Mastani",
    genre: "Historical Drama",
    release_year: "2015",
    director: "Sanjay Leela Bhansali",
    lead_actor: "Ranveer Singh",
    lead_actress: "Deepika Padukone",
    emoji: "⚔️",
    fact: "Ranveer Singh stayed in character for six months, isolating himself in a hotel room to maintain the mindset of Bajirao throughout filming.",
  },
  {
    name: "Sultan",
    genre: "Sports Drama",
    release_year: "2016",
    director: "Ali Abbas Zafar",
    lead_actor: "Salman Khan",
    lead_actress: "Anushka Sharma",
    emoji: "🤼",
    fact: "Salman Khan gained 18kg of muscle and then lost 15kg to portray different phases of the wrestler's life within a tight filming schedule.",
  },
  {
    name: "War",
    genre: "Action Thriller",
    release_year: "2019",
    director: "Siddharth Anand",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Vaani Kapoor",
    emoji: "💥",
    fact: "The film's climactic fight scene between Hrithik Roshan and Tiger Shroff took over 15 days to choreograph and 3 weeks to shoot.",
  },
  // Added movies as requested
  {
    name: "Uri: The Surgical Strike",
    genre: "Action",
    release_year: "2019",
    director: "Aditya Dhar",
    lead_actor: "Vicky Kaushal",
    lead_actress: "Yami Gautam",
    emoji: "🪖",
    fact: "The film's dialogue 'How's the Josh?' became a national catchphrase, and was even used by the Prime Minister of India in his speeches.",
  },
  {
    name: "Tanhaji",
    genre: "Historical Drama",
    release_year: "2020",
    director: "Om Raut",
    lead_actor: "Ajay Devgn",
    lead_actress: "Kajol",
    emoji: "⚔️",
    fact: "The film used cutting-edge 3D technology and VFX to recreate 17th century Maratha Empire, with over 70% of the film created through CGI.",
  },
  {
    name: "Fighter",
    genre: "Action",
    release_year: "2024",
    director: "Siddharth Anand",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Deepika Padukone",
    emoji: "✈️",
    fact: "Fighter was India's first aerial action film and featured real Indian Air Force aircraft and bases with special government permission.",
  },
  {
    name: "12th Fail",
    genre: "Biopic",
    release_year: "2023",
    director: "Vidhu Vinod Chopra",
    lead_actor: "Vikrant Massey",
    lead_actress: "Medha Shankar",
    emoji: "📚",
    fact: "The film was based on a true story and shot on real locations including Delhi's Mukherjee Nagar, where thousands of UPSC aspirants study.",
  },
  {
    name: "83",
    genre: "Sports Biopic",
    release_year: "2021",
    director: "Kabir Khan",
    lead_actor: "Ranveer Singh",
    lead_actress: "Deepika Padukone",
    emoji: "🏏",
    fact: "The real 1983 World Cup winning captain Kapil Dev personally trained Ranveer Singh for months to perfect his iconic bowling action.",
  },
  // Additional movies with actors/actresses already in the list
  {
    name: "Dil Chahta Hai",
    genre: "Drama",
    release_year: "2001",
    director: "Farhan Akhtar",
    lead_actor: "Aamir Khan",
    lead_actress: "Preity Zinta",
    emoji: "👬",
    fact: "This cult classic marked Farhan Akhtar's directorial debut and revolutionized the portrayal of urban youth and friendship in Bollywood.",
  },
  {
    name: "Jab Tak Hai Jaan",
    genre: "Romance",
    release_year: "2012",
    director: "Yash Chopra",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Katrina Kaif",
    emoji: "💑",
    fact: "This was legendary director Yash Chopra's final film before his death, ending a directorial career spanning over five decades.",
  },
  {
    name: "Ae Dil Hai Mushkil",
    genre: "Romance Drama",
    release_year: "2016",
    director: "Karan Johar",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Anushka Sharma",
    emoji: "💔",
    fact: "The film's title was taken from a song in the 1956 film 'CID' and explores the complex theme of unrequited love.",
  },
  {
    name: "Dear Zindagi",
    genre: "Coming-of-Age Drama",
    release_year: "2016",
    director: "Gauri Shinde",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Alia Bhatt",
    emoji: "🧠",
    fact: "The film was groundbreaking in Bollywood for its mature and destigmatizing portrayal of mental health therapy and emotional wellness.",
  },
  {
    name: "Sanju",
    genre: "Biopic",
    release_year: "2018",
    director: "Rajkumar Hirani",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Sonam Kapoor",
    emoji: "🎭",
    fact: "Ranbir Kapoor underwent 6 different looks to portray various phases of Sanjay Dutt's life, spending up to 5 hours in makeup daily.",
  },
  {
    name: "Dhoom 2",
    genre: "Action",
    release_year: "2006",
    director: "Sanjay Gadhvi",
    lead_actor: "Hrithik Roshan",
    lead_actress: "Aishwarya Rai",
    emoji: "🏍️",
    fact: "Hrithik Roshan performed all his own stunts in the film, including the dangerous surfing on a moving train sequence.",
  },
  {
    name: "Veer-Zaara",
    genre: "Romance",
    release_year: "2004",
    director: "Yash Chopra",
    lead_actor: "Shah Rukh Khan",
    lead_actress: "Preity Zinta",
    emoji: "🕊️",
    fact: "The film's music was composed using unreleased compositions by the late Madan Mohan, which were rearranged by his son Sanjeev Kohli.",
  },
  {
    name: "Cocktail",
    genre: "Romance",
    release_year: "2012",
    director: "Homi Adajania",
    lead_actor: "Saif Ali Khan",
    lead_actress: "Deepika Padukone",
    emoji: "🍸",
    fact: "Deepika Padukone's bold character Veronica marked a turning point in her career and was a complete departure from her previous roles.",
  },
  {
    name: "Rockstar",
    genre: "Musical Drama",
    release_year: "2011",
    director: "Imtiaz Ali",
    lead_actor: "Ranbir Kapoor",
    lead_actress: "Nargis Fakhri",
    emoji: "🎸",
    fact: "Ranbir Kapoor learned to play the guitar and lived with real musicians to prepare for his role as a troubled music sensation.",
  },
  {
    name: "Student of the Year",
    genre: "Coming of Age",
    release_year: "2012",
    director: "Karan Johar",
    lead_actor: "Sidharth Malhotra",
    lead_actress: "Alia Bhatt",
    emoji: "🏆",
    fact: "The film launched the careers of three major Bollywood stars: Alia Bhatt, Varun Dhawan, and Sidharth Malhotra.",
  },
  {
    name: "Karthik Calling Karthik",
    genre: "Psychological Thriller",
    release_year: "2010",
    director: "Vijay Lalwani",
    lead_actor: "Farhan Akhtar",
    lead_actress: "Deepika Padukone",
    emoji: "📞",
    fact: "The film explores dissociative identity disorder and was shot in reverse chronological order to help the actors understand their character arcs.",
  },
  {
    name: "Dil Dhadakne Do",
    genre: "Family Drama",
    release_year: "2015",
    director: "Zoya Akhtar",
    lead_actor: "Ranveer Singh",
    lead_actress: "Priyanka Chopra",
    emoji: "🚢",
    fact: "The film was shot on a cruise ship traveling through the Mediterranean, with the entire cast living on board during the 78-day schedule.",
  }
]