export const countryData = [
  {
    name: "United States",
    continent: "North America",
    language: "English",
    climate: "Temperate",
    population: "Very Large",
    emoji: "🇺🇸",
  },
  {
    name: "Canada",
    continent: "North America",
    language: "English",
    climate: "Continental",
    population: "Medium",
    emoji: "🇨🇦",
  },
  {
    name: "Brazil",
    continent: "South America",
    language: "Portuguese",
    climate: "Tropical",
    population: "Very Large",
    emoji: "🇧🇷",
  },
  {
    name: "Argentina",
    continent: "South America",
    language: "Spanish",
    climate: "Temperate",
    population: "Medium",
    emoji: "🇦🇷",
  },
  {
    name: "United Kingdom",
    continent: "Europe",
    language: "English",
    climate: "Temperate",
    population: "Medium",
    emoji: "🇬🇧",
  },
  {
    name: "France",
    continent: "Europe",
    language: "French",
    climate: "Mediterranean",
    population: "Medium",
    emoji: "🇫🇷",
  },
  {
    name: "Germany",
    continent: "Europe",
    language: "German",
    climate: "Temperate",
    population: "Large",
    emoji: "🇩🇪",
  },
  {
    name: "Spain",
    continent: "Europe",
    language: "Spanish",
    climate: "Mediterranean",
    population: "Medium",
    emoji: "🇪🇸",
  },
  {
    name: "Italy",
    continent: "Europe",
    language: "Italian",
    climate: "Mediterranean",
    population: "Medium",
    emoji: "🇮🇹",
  },
  {
    name: "China",
    continent: "Asia",
    language: "Chinese",
    climate: "Continental",
    population: "Very Large",
    emoji: "🇨🇳",
  },
  {
    name: "India",
    continent: "Asia",
    language: "Hindi",
    climate: "Tropical",
    population: "Very Large",
    emoji: "🇮🇳 ",
  },
  {
    name: "Japan",
    continent: "Asia",
    language: "Japanese",
    climate: "Temperate",
    population: "Large",
    emoji: "🇯🇵",
  },
  {
    name: "Australia",
    continent: "Oceania",
    language: "English",
    climate: "Arid",
    population: "Medium",
    emoji: "🇦🇺",
  },
  {
    name: "Egypt",
    continent: "Africa",
    language: "Arabic",
    climate: "Arid",
    population: "Large",
    emoji: "🇪🇬",
  },
  {
    name: "Nigeria",
    continent: "Africa",
    language: "English",
    climate: "Tropical",
    population: "Very Large",
    emoji: "🇳🇬",
  },
  {
    name: "Russia",
    continent: "Europe",
    language: "Russian",
    climate: "Continental",
    population: "Large",
    emoji: "🇷🇺",
  },
  {
    name: "Mexico",
    continent: "North America",
    language: "Spanish",
    climate: "Tropical",
    population: "Large",
    emoji: "🇲🇽",
  },
  {
    name: "Indonesia",
    continent: "Asia",
    language: "Indonesian",
    climate: "Tropical",
    population: "Very Large",
    emoji: "🇮🇩",
  },
  {
    name: "South Africa",
    continent: "Africa",
    language: "English",
    climate: "Temperate",
    population: "Medium",
    emoji: "🇿🇦",
  },
  {
    name: "Sweden",
    continent: "Europe",
    language: "Swedish",
    climate: "Continental",
    population: "Small",
    emoji: "🇸🇪",
  },
]

