export const fruitData = [
  {
    name: "Apple",
    taste: "Sweet",
    origin: "Central Asia",
    color: "Red",
    texture: "Crisp",
    emoji: "🍎",
    fact: "Apples float in water because they are 25% air by volume.",
  },
  {
    name: "Banana",
    taste: "Sweet",
    origin: "Southeast Asia",
    color: "Yellow",
    texture: "Soft",
    emoji: "🍌",
    fact: "Bananas are technically berries, while strawberries are not.",
  },
  {
    name: "Orange",
    taste: "Sweet-Sour",
    origin: "China",
    color: "Orange",
    texture: "Juicy",
    emoji: "🍊",
    fact: "The color orange was named after the fruit, not the other way around.",
  },
  {
    name: "Strawberry",
    taste: "Sweet",
    origin: "Europe",
    color: "Red",
    texture: "Soft",
    emoji: "🍓",
    fact: "Strawberries are the only fruit with seeds on the outside, with about 200 seeds per berry.",
  },
  {
    name: "Mango",
    taste: "Sweet",
    origin: "South Asia",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🥭",
    fact: "Mangoes are related to cashews and pistachios, and are the most consumed fruit in the world.",
  },
  {
    name: "Pineapple",
    taste: "Sweet-Sour",
    origin: "South America",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🍍",
    fact: "Pineapples take almost 3 years to grow to full size.",
  },
  {
    name: "Watermelon",
    taste: "Sweet",
    origin: "Africa",
    color: "Green",
    texture: "Juicy",
    emoji: "🍉",
    fact: "Watermelons are 92% water and were used as canteens in the desert by early explorers.",
  },
  {
    name: "Grape",
    taste: "Sweet",
    origin: "Middle East",
    color: "Purple",
    texture: "Juicy",
    emoji: "🍇",
    fact: "There are over 8,000 varieties of grapes, and they are technically berries.",
  },
  {
    name: "Lemon",
    taste: "Sour",
    origin: "Southeast Asia",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🍋",
    fact: "Lemons contain more sugar than strawberries, but their acidity masks the sweetness.",
  },
  {
    name: "Peach",
    taste: "Sweet",
    origin: "China",
    color: "Orange",
    texture: "Juicy",
    emoji: "🍑",
    fact: "Peaches are members of the rose family, along with apples and almonds.",
  },
  {
    name: "Kiwi",
    taste: "Sweet-Sour",
    origin: "China",
    color: "Brown",
    texture: "Soft",
    emoji: "🥝",
    fact: "Kiwi fruits contain more vitamin C than oranges and more potassium than bananas.",
  },
  {
    name: "Cherry",
    taste: "Sweet",
    origin: "Europe",
    color: "Red",
    texture: "Juicy",
    emoji: "🍒",
    fact: "A cherry tree can produce about 7,000 cherries in a season.",
  },
  {
    name: "Avocado",
    taste: "Mild",
    origin: "Mexico",
    color: "Green",
    texture: "Creamy",
    emoji: "🥑",
    fact: "Avocados are a fruit, not a vegetable, and contain more fat than any other fruit.",
  },
  {
    name: "Blueberry",
    taste: "Sweet",
    origin: "North America",
    color: "Blue",
    texture: "Juicy",
    emoji: "🫐",
    fact: "Blueberries are one of the few naturally blue foods on earth.",
  },
  {
    name: "Coconut",
    taste: "Sweet",
    origin: "Southeast Asia",
    color: "Brown",
    texture: "Firm",
    emoji: "🥥",
    fact: "Coconut water can be used as a substitute for blood plasma in emergencies.",
  },
  {
    name: "Papaya",
    taste: "Sweet",
    origin: "Central America",
    color: "Orange",
    texture: "Soft",
    emoji: "🧡",
    fact: "Papaya enzymes are used in meat tenderizers and beauty products.",
  },
  {
    name: "Guava",
    taste: "Sweet",
    origin: "Central America",
    color: "Green",
    texture: "Firm",
    emoji: "💚",
    fact: "Guavas contain 4 times more vitamin C than oranges.",
  },
  {
    name: "Pomegranate",
    taste: "Sweet-Tart",
    origin: "Middle East",
    color: "Red",
    texture: "Juicy",
    emoji: "❤️",
    fact: "Each pomegranate can contain up to 1,400 seeds, each surrounded by a juicy aril.",
  },
  {
    name: "Dragonfruit",
    taste: "Mild",
    origin: "Central America",
    color: "Pink",
    texture: "Soft",
    emoji: "💗",
    fact: "Dragon fruit comes from a type of cactus and blooms only at night.",
  },
  {
    name: "Pear",
    taste: "Sweet",
    origin: "Europe",
    color: "Green",
    texture: "Juicy",
    emoji: "🍐",
    fact: "Pears are one of the few fruits that ripen better off the tree than on it.",
  },
  {
    name: "Plum",
    taste: "Sweet",
    origin: "Europe",
    color: "Purple",
    texture: "Juicy",
    emoji: "🍑",
    fact: "Plums can be dried to make prunes and have been cultivated for over 2,000 years.",
  },
  {
    name: "Lychee",
    taste: "Sweet",
    origin: "China",
    color: "Red",
    texture: "Juicy",
    emoji: "🍒",
    fact: "Lychees have been cultivated in China for more than 2,000 years and were once used as tribute to emperors.",
  },
  {
    name: "Jackfruit",
    taste: "Sweet",
    origin: "South Asia",
    color: "Yellow",
    texture: "Firm",
    emoji: "🍈",
    fact: "Jackfruit is the largest tree-borne fruit in the world, weighing up to 80 pounds (36 kg).",
  },
  {
    name: "Starfruit",
    taste: "Sweet-Tart",
    origin: "Southeast Asia",
    color: "Yellow",
    texture: "Crisp",
    emoji: "⭐🍈",
    fact: "When cut crosswise, starfruit reveals a perfect five-pointed star shape, which is how it got its name.",
  },
  {
    name: "Raspberry",
    taste: "Sweet-Tart",
    origin: "Europe",
    color: "Red",
    texture: "Juicy",
    emoji: "🍓",
    fact: "Raspberries are actually clusters of many small fruits called drupelets, each containing one seed.",
  },
  {
    name: "Custard Apple",
    taste: "Sweet",
    origin: "India",
    color: "Green",
    texture: "Soft",
    emoji: "🍈",
    fact: "Custard apples contain high levels of vitamin C and are known for their creamy texture similar to custard.",
  },
  {
    name: "Gooseberry",
    taste: "Tart",
    origin: "Europe",
    color: "Green",
    texture: "Firm",
    emoji: "🍇",
    fact: "Gooseberries were once banned in the US because they were thought to spread a disease harmful to pine trees.",
  },
  {
    name: "Passion Fruit",
    taste: "Tart",
    origin: "South America",
    color: "Purple",
    texture: "Soft",
    emoji: "🥭",
    fact: "Passion fruit got its name from Christian missionaries who saw the flower's structure as symbolizing Christ's passion.",
  },
  {
    name: "Cranberry",
    taste: "Tart",
    origin: "North America",
    color: "Red",
    texture: "Firm",
    emoji: "🍒",
    fact: "Cranberries don't grow in water but on vines in bogs; fields are flooded only for harvesting.",
  },
  {
    name: "Mulberry",
    taste: "Sweet-Tart",
    origin: "Asia",
    color: "Purple",
    texture: "Juicy",
    emoji: "🍇",
    fact: "Mulberry leaves are the only food silkworms will eat, making them essential to silk production.",
  },
  {
    name: "Tamarind",
    taste: "Sweet-Sour",
    origin: "Africa",
    color: "Brown",
    texture: "Sticky",
    emoji: "🌰",
    fact: "Tamarind is a key ingredient in Worcestershire sauce and has been used in traditional medicine for centuries.",
  },
];