export const fruitData = [
  {
    name: "Apple",
    taste: "Sweet",
    origin: "Central Asia",
    color: "Red",
    texture: "Crisp",
    emoji: "🍎",
  },
  {
    name: "Banana",
    taste: "Sweet",
    origin: "Southeast Asia",
    color: "Yellow",
    texture: "Soft",
    emoji: "🍌",
  },
  {
    name: "Orange",
    taste: "Sweet-Sour",
    origin: "China",
    color: "Orange",
    texture: "Juicy",
    emoji: "🍊",
  },
  {
    name: "Strawberry",
    taste: "Sweet",
    origin: "Europe",
    color: "Red",
    texture: "Soft",
    emoji: "🍓",
  },
  {
    name: "Mango",
    taste: "Sweet",
    origin: "South Asia",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🥭",
  },
  {
    name: "Pineapple",
    taste: "Sweet-Sour",
    origin: "South America",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🍍",
  },
  {
    name: "Watermelon",
    taste: "Sweet",
    origin: "Africa",
    color: "Green",
    texture: "Juicy",
    emoji: "🍉",
  },
  {
    name: "Grape",
    taste: "Sweet",
    origin: "Middle East",
    color: "Purple",
    texture: "Juicy",
    emoji: "🍇",
  },
  {
    name: "Lemon",
    taste: "Sour",
    origin: "Southeast Asia",
    color: "Yellow",
    texture: "Juicy",
    emoji: "🍋",
  },
  {
    name: "Peach",
    taste: "Sweet",
    origin: "China",
    color: "Orange",
    texture: "Juicy",
    emoji: "🍑",
  },
  {
    name: "Kiwi",
    taste: "Sweet-Sour",
    origin: "China",
    color: "Brown",
    texture: "Soft",
    emoji: "🥝",
  },
  {
    name: "Cherry",
    taste: "Sweet",
    origin: "Europe",
    color: "Red",
    texture: "Juicy",
    emoji: "🍒",
  },
  {
    name: "Avocado",
    taste: "Mild",
    origin: "Mexico",
    color: "Green",
    texture: "Creamy",
    emoji: "🥑",
  },
  {
    name: "Blueberry",
    taste: "Sweet",
    origin: "North America",
    color: "Blue",
    texture: "Juicy",
    emoji: "🫐",
  },
  {
    name: "Coconut",
    taste: "Sweet",
    origin: "Southeast Asia",
    color: "Brown",
    texture: "Firm",
    emoji: "🥥",
  },
  {
    name: "Papaya",
    taste: "Sweet",
    origin: "Central America",
    color: "Orange",
    texture: "Soft",
    emoji: "🧡",
  },
  {
    name: "Guava",
    taste: "Sweet",
    origin: "Central America",
    color: "Green",
    texture: "Firm",
    emoji: "💚",
  },
  {
    name: "Pomegranate",
    taste: "Sweet-Tart",
    origin: "Middle East",
    color: "Red",
    texture: "Juicy",
    emoji: "❤️",
  },
  {
    name: "Dragonfruit",
    taste: "Mild",
    origin: "Central America",
    color: "Pink",
    texture: "Soft",
    emoji: "💗",
  },
  {
    name: "Pear",
    taste: "Sweet",
    origin: "Europe",
    color: "Green",
    texture: "Juicy",
    emoji: "🍐",
  },
]

