export const vehicleData = [
  {
    name: "Sedan",
    type: "Car",
    fuel: "Petrol",
    terrain: "Road",
    capacity: "3-5 people",
    emoji: "🚗",
  },
  {
    name: "Motorcycle",
    type: "Motorcycle",
    fuel: "Petrol",
    terrain: "Road",
    capacity: "1-2 people",
    emoji: "🏍️",
  },
  {
    name: "Bicycle",
    type: "Bicycle",
    fuel: "None",
    terrain: "Road",
    capacity: "1-2 people",
    emoji: "🚴",
  },
  {
    name: "Airplane",
    type: "Airplane",
    fuel: "Jet Fuel",
    terrain: "Air",
    capacity: "More than 10",
    emoji: "✈️",
  },
  {
    name: "Boat",
    type: "Boat",
    fuel: "Diesel",
    terrain: "Water",
    capacity: "6-10 people",
    emoji: "🚤",
  },
  {
    name: "Truck",
    type: "Truck",
    fuel: "Diesel",
    terrain: "Road",
    capacity: "More than 10",
    emoji: "🚛",
  },
  {
    name: "Bus",
    type: "Bus",
    fuel: "Diesel",
    terrain: "Road",
    capacity: "More than 10",
    emoji: "🚌",
  },
  {
    name: "Helicopter",
    type: "Helicopter",
    fuel: "Aviation Fuel",
    terrain: "Air",
    capacity: "4-6 people",
    emoji: "🚁",
  },
  {
    name: "Submarine",
    type: "Submarine",
    fuel: "Nuclear/Diesel",
    terrain: "Water",
    capacity: "More than 10",
    emoji: "🚢",
  },
  {
    name: "Sports Car",
    type: "Car",
    fuel: "Petrol",
    terrain: "Road",
    capacity: "2 people",
    emoji: "🏎️",
  },
  {
    name: "Electric Scooter",
    type: "Scooter",
    fuel: "Electric",
    terrain: "Road",
    capacity: "1 person",
    emoji: "🛴",
  },
  {
    name: "SUV",
    type: "Car",
    fuel: "Petrol/Diesel",
    terrain: "Road & Off-Road",
    capacity: "5-7 people",
    emoji: "🚙",
  },
  {
    name: "Tractor",
    type: "Agricultural Vehicle",
    fuel: "Diesel",
    terrain: "Field",
    capacity: "1-2 people",
    emoji: "🚜",
  },
  {
    name: "Train",
    type: "Train",
    fuel: "Diesel/Electric",
    terrain: "Rail",
    capacity: "More than 10",
    emoji: "🚆",
  },
  {
    name: "ATV",
    type: "All-Terrain Vehicle",
    fuel: "Petrol",
    terrain: "Off-Road",
    capacity: "1-2 people",
    emoji: "🏎️",
  },
  {
    name: "Tanker",
    type: "Truck",
    fuel: "Diesel",
    terrain: "Road",
    capacity: "More than 10",
    emoji: "🚛",
  },
  {
    name: "Fighter Jet",
    type: "Jet",
    fuel: "Aviation Fuel",
    terrain: "Air",
    capacity: "1 person",
    emoji: "✈️",
  },
  {
    name: "Yacht",
    type: "Luxury Boat",
    fuel: "Diesel",
    terrain: "Water",
    capacity: "6-10 people",
    emoji: "🛥️",
  },
  {
    name: "Hovercraft",
    type: "Hovercraft",
    fuel: "Diesel",
    terrain: "Water & Land",
    capacity: "More than 10",
    emoji: "🛸",
  }
];
